### ISSUE TITLE
commit confirmation message missing

### ISSUE THREAD

**Issue by ctschroeder** [gucorpling/gitdox#115]
I'm loving the ability to edit metadata. THANK YOU.  

Since the recent updates, now when I commit to GitHub, I do not see a red message confirming the commit and providing the commit number.  Also the commit message stays in the little window even after the commit.  This all made me wonder if I was committing correctly, or if the commit was really "committing."  I've checked the GitHub repositories, and it appears that the commits are being received in GitHub. 

Is there any way to add back that little commit message, so the user knows it's gone through?  Many thanks!  (Not a huge priority, and hopefully easy.)

**Comment by amir-zeldes** [comment]
@lgessler - could you take a look when you have a chance? This used to be serialized on CGI submit while the page was being generated. The async is great but users need some feedback on commit success, and the commit message box should be cleared if it was successful.

**Comment by ctschroeder** [comment]
thanks for checking on this. Also really really loving the other upgrades, @lgessler and @amir-zeldes.

**Comment by lgessler** [comment]
@amir-zeldes we can close this since it's been observed to work again (#122)
