### ISSUE TITLE
Conversions out of GitDox possibly not preserving docnames

### ISSUE THREAD

**Issue by ctschroeder** [gucorpling/gitdox#119]
Some of the docs posted to Scriptorium's ANNIS instance have incorrect document names -- they seem based on different data than the GitDox doc name (or maybe the first namespace of the doc name?).  (See A22 and Victor docs for examples.) I'm wondering if there is something going on with the conversion process.  

This is potentially urgent.  Thanks so much!

**Comment by amir-zeldes** [comment]
Hm, this is a regression of an old SNP bug truncating document names to the first period. I'll look into it.

**Comment by amir-zeldes** [comment]
Confirmed SNP-related, not a GitDox bug - now fixed. For the record this is related to:

https://github.com/korpling/treetagger-emf-api/pull/2
