### ISSUE TITLE
unable to create new document from cloned metadata

### ISSUE THREAD

**Issue by ctschroeder** [gucorpling/gitdox#144]
I tried from cloning from two different documents in the apophthegmata patrum corpus and received the following error both time
Loading Error
For some reason, this page failed to load.

Please send this to your system administrator:

Traceback (most recent call last):
  File "/var/www/html/gitdox/scriptorium/editor.py", line 417, in open_main_server
    print(load_page(user, admin, theform).encode("utf8"))
  File "/var/www/html/gitdox/scriptorium/editor.py", line 171, in load_page
    save_meta(int(doc_id), m_key.decode("utf8"), m_val.decode("utf8"))
  File "/usr/lib64/python2.6/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xee' in position 3: ordinal not in range(128)

Thank you!!

**Comment by lgessler** [comment]
@ctschroeder thanks for the report, please try this again, I think I've fixed it

@amir-zeldes I solved this by changing

```py
save_meta(int(doc_id), m_key.decode("utf8"), m_val.decode("utf8"))
```

to

```py
save_meta(int(doc_id), m_key, m_val)
```

I've been meaning to ask you, when is(n't) it appropriate to use decode/encode, is it easy to explain? Whenever one of these encoding errors pops up I just mindlessly add or remove the occurrence of decode or encode, but I don't really understand how this works.

**Comment by ctschroeder** [comment]
Thanks so much Luke. I am on family vacation this week and will test it as soon as I can. Take good care.

**Comment by amir-zeldes** [comment]
Thanks @lgessler - I'm a little surprised we still run into encoding problems, but I tested and it seems to work fine. Can you commit this to dev?

**Comment by ctschroeder** [comment]
this is working and can be closed
