### ISSUE TITLE
Re-work metatable

### ISSUE THREAD

**Issue by amir-zeldes** [gucorpling/gitdox#5]
Replace pop-up with fillable table with 'new entry' as last row.

**Comment by amir-zeldes** [comment]
Consider avoiding the `<datalist>` control due to incomplete browser support (Safari)

**Comment by ctschroeder** [comment]
Bumping this up per our discussion in DC that this was doable in time for this publication round. Editing metadata using the current interface is time-consuming during the review process.

**Comment by amir-zeldes** [comment]
I've re-prioritized with @lgessler to work on something else important, which is having auto-validation of TEI export (i.e. the dashboard will show the result of converting each document to TEI and running TEI-XSD validation on it). That's one of the things we currently have no automated way of dealing with, but would be really useful for catching errors. 

I agree the metatable improvement would be a nice feature though, so it would be nice for the future, but probably not in time for this month's release.

**Comment by ctschroeder** [comment]
Thanks for the update. This is a hassle, so if we can prioritize for next round it would really help. Thanks.

**Comment by lgessler** [comment]
Done in #109

**Comment by amir-zeldes** [comment]
@lgessler : One small enhancement before closing: can we allow edit, rather than just add/delete? The validation table editor has this enabled, so it would be nice if the editor.py metatable also allowed the edit operation.
