### ISSUE TITLE
Allow multiple columns of same annotation

### ISSUE THREAD

**Issue by amir-zeldes** [gucorpling/gitdox#69]
Needed for nested entity spans: two columns may carry an identical header such as `entity`. 

Note this complicates several components:
  * Export behavior: adapt code in modules/ether.py to accept multiple simultaneously open spans, not just open-close events
  * Import behavior: ditto - assign to new column if span is already (partially) populated in lowest index column of same type
  * Validation behavior: all operators still apply, but multiple columns need to be checked. Function converting letter<>col-num must be revised to return lists and behave appropriately

**Comment by lgessler** [comment]
Fixed in #100
