### ISSUE TITLE
Breaking changes in github3 1.2.0

### ISSUE THREAD

**Issue by lgessler** [gucorpling/gitdox#73]
There is at least one breaking change (from the perspective of this project) in the latest version of github3.py. 

In [this line in `gitdox_git`](https://github.com/gucorpling/gitdox/blob/e42469f60ab0cffd2b27c6ebe2713749096f968c/modules/gitdox_git.py#L28), there is reference to a `contents` attribute:

```python
		contents_object = repository.contents(file_info)
```

However, this function has been split into `file_contents` and `directory_contents` in github3.py 1.2.0. 

GitDOX must have been written assuming an earlier version of github3.py. We should either lock our version of gh3 in our `requirements.txt` or find all the breaking changes that affect GitDOX and fix them.

edit: this code works fine for github3.py==0.9.3, so we could just write that in the requirements

**Comment by amir-zeldes** [comment]
Ultimately we may need to upgrade, especially if the GitHub API becomes incompatible with 0.9.3, but at the moment fixing the version seems like the cheaper option, so let's do that. This should be closed once #72 is merged.

**Comment by amir-zeldes** [comment]
Fixed in #72
