### ISSUE TITLE
validate_spreadsheets.py does not return valid JSON on fresh install

### ISSUE THREAD

**Issue by lgessler** [gucorpling/gitdox#75]
After a fresh install, when I log in for the first time, [index.js](https://github.com/gucorpling/gitdox/blob/master/js/index.js#L64) alerts: "SyntaxError: Unexpected end of JSON input". The value of the HTTP response is a string with the carriage return symbol in it, which is indeed not valid JSON. This response seems to be coming from the [`validate_all_docs` function in validate_spreadsheets.py](https://github.com/gucorpling/gitdox/blob/master/modules/validate_spreadsheet.py#L82), though I'm not sure what exactly is causing the issue.

**Comment by amir-zeldes** [comment]
This might just be a lack of insurance against an empty table, there should be a handler to check for zero rows and return a sensible, empty json object.

**Comment by amir-zeldes** [comment]
Fixed in c7f5efe2b92da2beba7ebb94b38826e9be607996 (now logs to console)
