### ISSUE TITLE
move "new document" button to top

### ISSUE THREAD

**Issue by ctschroeder** [gucorpling/gitdox#80]
This is NOT urgent in any way.  Would it be possible to move the "new" button to create a new document to the top of the screen somewhere?  When we have a long list of docs, you have to scroll all the way down to add a new document.  Thanks for considering this request!

**Comment by lgessler** [comment]
can do! will get that in this week

**Comment by amir-zeldes** [comment]
Closed via c08cf6e0725c3e5a34d90449650a31a440fe6eba
